version: "3.8"

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: master
    ports:
      - "8000:5000"
    networks:
      - cluster_net

  secondary1:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    container_name: secondary1
    ports:
      - "8001:5000"
    networks:
      - cluster_net
    environment:
      REPLICA_DELAY: 5
      MASTER_URL: http://master:5000
      SECONDARY_URL: http://secondary1:5000
    depends_on:
      - master

  secondary2:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    container_name: secondary2
    ports:
      - "8002:5000"
    networks:
      - cluster_net
    environment:
      REPLICA_DELAY: 0
      MASTER_URL: http://master:5000
      SECONDARY_URL: http://secondary2:5000
    depends_on:
      - master

networks:
  cluster_net:
    driver: bridge
